[SPBU-21.B10] Task_3.3 Копань Артём
ArtyomKopan/Programming_homeworks_1 pull request #11
Opened 2021-10-10 16:27 UTC by ArtyomKopan

2021-10-26 10:10 UTC, SpirinEgor requested changes
А где тут перевод в двоичную систему? Спасибо, что не просто на 1 в цикле уменьшаешь хотя бы :)

2021-10-26 20:28 UTC, ArtyomKopan commented
Я не могу понять, как работать с числом в двоичной системе. В строку его переводить, что ли? Или нужно сделать отдельную структуру с представлением двоичного числа в виде массива int? (я пытался так сделать, но не получилось реализовать сложение, вернее, учесть все добавления разрядов при переполнении и т.п.)

2021-10-28 15:40 UTC, SpirinEgor commented
Конечную структуру для представления ты можешь выбрать сам. Как тебе удобнее. Удобнее всего сделать массив интов или чаров размером 32. В случае переполнения та крайняя единичка просто отбрасывается (ничего не надо делать то есть).

2021-11-08 08:59 UTC, SpirinEgor requested changes
Довольно странная организация функций умножений. Но особенно плохо -- дублирования кода в сложениях

2021-11-08 08:59 UTC, SpirinEgor commented on Homework3/binary_number.c
> +void add(int* a, int* b)
А чем отличается от sum? Кажется одну из функций можно переиспользовать в другой

2021-11-08 08:59 UTC, SpirinEgor commented on Homework3/task_3.3.c
> +int* multiply(int* a, int* b)
Так может эти функции тоже в модуль спрятать?

2021-11-09 21:23 UTC, SpirinEgor approved these changes

2021-11-09 21:24 UTC, merged