[SPBU-21.B10] Task 3.1 Копань Артём
ArtyomKopan/Programming_homeworks_1 pull request #15
Opened 2021-10-27 20:54 UTC by ArtyomKopan

2021-10-28 15:38 UTC, SpirinEgor requested changes

2021-10-28 15:38 UTC, SpirinEgor commented on Homework3/binary_number.c
> +    if (b[0] == 1)
Я обычно предпочитаю в таких случаях делать
```c
if (b[0] == 0)
    return;
...
```

Не возникает лишних вложенностей, код попроще выглядит. А ты ещё и скобками не пользуешься, вообще выглядит всё поехавшим

2021-10-28 15:38 UTC, SpirinEgor commented on Homework3/binary_number.c
> +                b[i] = 0;
```c
b[i] = 1 - b[i];
```

2021-10-28 15:38 UTC, SpirinEgor commented on Homework3/binary_number.c
> +    }
Это всё можно сделать одним циклом, в котором 2 строчки.

2021-10-28 15:38 UTC, SpirinEgor commented on Homework3/binary_number.c
> +    if (carry == 1) {
А что это за случай? Если я правильно понял, то это переполнение и эта 1 просто "откидывается"

2021-10-28 15:38 UTC, SpirinEgor commented on Homework3/binary_number.c
> +        x = 2 * x + b[i];
Вот это ты очень круто сделал 👍

2021-10-28 15:38 UTC, SpirinEgor commented on Homework3/binary_number.h
> +#define MAX_NUMBER_LENGTH 33 // 32 бита под число + 1 бит под знак
Ну или можно придерживаться инта и держать 32 бита, кажется более интуитивным.

2021-10-28 15:38 UTC, SpirinEgor commented on Homework3/task_3.1.c
> +        printf("-");
```c
char sign = (b[0] == 0) ? '+' : '-';
```
Ну или можно сразу в принт обернуть

2021-10-28 15:38 UTC, SpirinEgor commented on Homework3/task_3.1.c
> +        printf("-");
А почему в двоичном представлении вообще знак печатается?

2021-10-28 15:41 UTC, ArtyomKopan commented on Homework3/task_3.1.c
> +        printf("-");
А разве так нельзя, если выводить в прямом коде? Допустим, в Python, если написать print(bin(-10)), то выведется -0b1010

2021-10-28 15:44 UTC, ArtyomKopan commented on Homework3/binary_number.c
> +    if (carry == 1) {
Нет, это на случай, если у числа меняется знак. Допустим, складываем -25 и 36, и после того, как мы сложили все цифры, остаётся лишняя единичка. Её ведь нужно прибавить к числу

2021-11-07 18:09 UTC, SpirinEgor commented on Homework3/task_3.1.c
> +        printf("-");
Ну у нас тут не пары питона, чтобы делать как там. Да и референс тоже так себе, то что там пишут знак не делает это самым верным решением. Мы прошли, что прямой код далеко не самый выгодный, поэтому и хранить в нём числа не надо.

2021-11-07 18:11 UTC, SpirinEgor approved these changes

2021-11-07 18:11 UTC, merged