[SPBU-21.B10] Task 5.1 Копань Артём
ArtyomKopan/Programming_homeworks_1 pull request #17
Opened 2021-11-08 21:42 UTC by ArtyomKopan

2021-12-16 09:34 UTC, ArtyomLobanov requested changes
По хорошему компаратор нужно хранить в TreeMap, чтобы у пользователя была возможность как-то адекватно сортировать нетривиальные объекты. Впрочем, конкретно в первой задаче работает и так, так что в целом ок.

2021-12-16 09:34 UTC, ArtyomLobanov commented on Homework5/AVL_tree.c
> +        deleteTree(tree->right);
Раз deleteTree за счёт первого if-а корректно работает с нулевыми указателями, то отдельно проверять существование детей не требуется

2021-12-16 09:34 UTC, ArtyomLobanov commented on Homework5/AVL_tree.c
> +    return compare(tree->key, key) >= 0 ? tree->key : getLowerBound(tree->right, key);
![image](https://user-images.githubusercontent.com/9067686/146344306-8a0e94d2-2c26-4c03-8f2c-37d809ac5b40.png)
Рассмотрим такое дерево. Хотим найти lower bound от 3. Стартуем от корня, сравниваем ключ (т.е. 3) со значением в текущей вершине (т.е. 10), понимаем, что значение в вершине больше ключа и возвращаем `tree->key` т.е. 10. Однако, методом пристального взгляда можно понять, что правильный ответ – 5. Исправьте логику работы.

2021-12-16 09:34 UTC, ArtyomLobanov commented on Homework5/AVL_tree.c
> +    return compare(tree->key, key) > 0 ? tree->key : getUpperBound(tree->right, key);
Тут такие же проблемы,

2021-12-16 09:34 UTC, ArtyomLobanov commented on Homework5/task_5.1.c
> +                store = put(store, wrapInt(size), wrapInt(count));
Если на складе было 10 пар обуви 40го размера, а затем туда добавили ещё 30, то сколько теперь пар этого размера хранится на складе?

2021-12-16 20:57 UTC, ArtyomKopan commented on Homework5/AVL_tree.c
> +    return compare(tree->key, key) >= 0 ? tree->key : getLowerBound(tree->right, key);
Не могу понять, как написать правильно. Помогите, пожалуйста

2021-12-21 10:40 UTC, ArtyomLobanov requested changes

2021-12-21 10:40 UTC, ArtyomLobanov commented on Homework5/AVL_tree.c
> +    return hasKey(tree->left, key) || hasKey(tree->right, key);
Ваш поиск ключа работает за линейное время. Сравнив искомый ключ с ключом, хранящимся в вершине, мы можем однозначно определить, в каком поддереве нужно продолжить поиск.

2021-12-21 10:40 UTC, ArtyomLobanov commented on Homework5/AVL_tree.c
> +        return !isNone(getLowerBound(tree->left, key)) ? getLowerBound(tree->left, key) : tree->key;
```cpp
else if (tree->comparator(tree->key, key) == 1) // т.е. tree->key > key
    return getLowerBound(tree->right, key);
```
"Если ключ в вершине больше, чем заданный ключ, то продолжаем поиск верхней границы в правом поддереве"
Почему в правом? Мы же ищем наименьшую из верхних границ. Ключ tree->key – уже верхняя граница. Искать большую границу смысла нет. А вот границу меньше  вполне можно.

```cpp
else
    return !isNone(getLowerBound(tree->left, key)) ? getLowerBound(tree->left, key) : tree->key;
```
И опять же время работы у вас не логарифмическое т.к. вы делаете два полноценных рекурсивных вызова. Если время работы от глубины дерева обозначить T(h) = T(h-1) + T(h-1) + O(1) т.е. в сумме получаем экспоненциальное время от глубины дерева = линейное время от размера дерева.

2021-12-21 10:40 UTC, ArtyomLobanov commented on Homework5/AVL_tree.c
> +        return !isNone(getLowerBound(tree->left, key)) ? getLowerBound(tree->left, key) : tree->key;
Просто сохраните результат рекурсивного вызова в локальную переменную.

2021-12-21 10:40 UTC, ArtyomLobanov commented on Homework5/AVL_tree.c
> +        return !isNone(getUpperBound(tree->left, key)) ? getUpperBound(tree->left, key) : tree->key;
Аналогичные замечания к UpperBound

2021-12-24 07:25 UTC, ArtyomLobanov approved these changes
Ок

2021-12-24 07:25 UTC, ArtyomLobanov commented on Homework5/AVL_tree.c
> +            return balance(treeLeft);
Кстати, tree->left можно даже не балансировать – мы его не трогали, а значит оно должно уже находиться в балансе.

2021-12-24 07:25 UTC, ArtyomLobanov commented on Homework5/AVL_tree.c
> +    else if (tree->comparator(oldKey, tree->key) > 0)
Нельзя так просто взять и поменять ключ у вершины в дереве. Это ломает инвариант дерева – откуда нам теперь знать, что вершины в левом поддереве меньше нового ключа, а в правом – больше? И функция balance вас тут не спасёт т.к. она отвечает только за сбалансированность дерева. Если вам так хочется поменять один ключ на другой, то сначала удалите первый, а затем добавьте второй. Будет работать за логарифм и ничего не ломать.
Благо, вы, кажется, нигде эту функцию не используете

2021-12-24 07:34 UTC, merged