[SPBU-21.B10] Task 6.1 Копань Артём
ArtyomKopan/Programming_homeworks_1 pull request #18
Opened 2021-11-14 21:21 UTC by ArtyomKopan

2021-12-14 03:05 UTC, ArtyomLobanov requested changes
1) Добавьте поддержку расширения структуры данных при достижении критического уровня заполненности. 
2) Передавайте в конструкторе hash-таблицы кроме функции хеширования ещё и функцию сравнения, которая будет сравнивать ключи не по указателю а по значению
3) Я буду настаивать на классическом интерфейсе ассоциативного массива т.е. каждому ключу должно соответствовать ровно одно значение. Если при вызове функции put передаётся уже присутствующий ключ, то старое ассоциированное с ним значение затирается

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +        return power(a, n / 2) * power(a, n / 2);
Это выглядит почти как алгоритм для возведения числа в степень за логарифм от показателя, но вот здесь вы свернули не туда и получили линейное время работы. Зачем вам рекурсивно два раза считать одно и то же?
```cpp
int tmp = power(a, n / 2);
return tmp * tmp;
```
(Для красоты можно вынести возведение в квадрат в отдельную функцию square(int x))

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +    memcpy(&x, &h, sizeof(x));
У вас программа с SegFault не падала? Вы пытаетесь записать 64 бита переменной x (зависит от платформы, конечно, но чаще всего float - 32 бита, double - 64 бита, long double - 128 бит) в 32-битную целочисленную переменную

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +        return power(a, n / 2) * power(a, n / 2);
Кстати, у вас быстро переполнится int, поэтому для подсчёта хешей лучше было бы сразу считать степень по заданному модулю.

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +        hash += (string[i] * power(HASH_POLYNOMIAL_PARAMETER, length - i)) % MOD;
Намного удобнее считать не сумму `p^i * s[i]`, а сумму `p^(n - i) * s[i]`. Тогда подсчёт хеша строки можно записать сильно проще:
```cpp
for (int i = 0; i < length; ++i) 
    hash = (hash * HASH_POLYNOMIAL_PARAMETER + s[i]) % MOD;
```
Тогда не возникает необходимости считать нужную степень каждый раз с нуля. Альтернативно, можно завести дополнительную переменную и хранить в ней актуальную степень множителя.
```cpp
for (int i = 0; i < length; ++i) {
    hash = (hash + s[i] * multiplier) % MOD;
    multiplier = (multiplier * HASH_POLYNOMIAL_PARAMETER) % MOD;
}
```
Если что, `(a * b) mod c = ((a mod c) * (b mod c)) mod c`

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +    return (hash(pair->first) + hash(pair->second)) % MOD;
В вашем случает пара (a, b) будет иметь такой же хеш, как и пара (b, a). Если хеш начинает отображать какие-то осмысленные свойства элементов, то скорее всего что-то идёт не так и при применении возникнет куча коллизий. Домножьте хеш одного из элементов на какое-нибудь простое число.

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +        listHash += ((hash(key) + hash(value)) % MOD) * power(HASH_POLYNOMIAL_PARAMETER, getListSize(list) - i) % MOD;
Аналогично, считая степень каждый раз с нуля вы умножаете асимптотику времени работы на лишний логарифм (а в вашем случае из-за баги вообще на линию)

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +        listHash += ((hash(key) + hash(value)) % MOD) * power(HASH_POLYNOMIAL_PARAMETER, getListSize(list) - i) % MOD;
И хеши ключа и значения тоже с каким нибудь множителем складывайте `hash(key) + 239 * hash(value)`

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +        free(map->hashTable[i]);
Но в HashMapElement же хранится список значений. Память из под него вы никак не освобождаете

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +List* getHashMapElements(HashMap* map, Value key)
Ситуация, в которой в ассоциативном массиве хранится несколько значений по одинаковому ключу звучит как минимум специфично. В нормальном состоянии от структуры такого не ждёшь. Почему вы реализовали функциональность поиск ключа именно так?

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +        if (equals(key, getListElement(map->hashTable[hashElement]->list, i)->key))
Проверять ключи на равенство стандартным equals, наверное, не очень хорошо т.к. ссылочные типы он сравнивает только по адресу, а хеш мы считаем как-то интеллектуально исходя из содержания данных по указателю. В результате, во-первых, не будет главный постулат хеширования – "если объекты равны, то и их хеши равны", а во-вторых нельзя будет использовать сложные типы в качестве ключей т.к. с точки зрения функции equals два копии одного и того же списка будут различными ключами из-за несовпадения адресов, где они лежат в памяти

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +            deleteListElement(map->hashTable[hashElement]->list, i);
1) В нормальной жизни ключ может встретиться нам только один раз, поэтому после удаления можно сразу делать return
2) Если считать, что ключи могут повторяться, то у вас тут бага. Скажем, имеется список ключей [1, 1, 2]. Вы хотите удалить ключ 1. В цикле при i=0 вы находите первый совпадающий ключ, удаляете его из списка (теперь список выглядит так: [1, 2], затем в цикле инкрементируется переменная i и вы переходите к следующей итерации, на которой рассматриваете элемент с индексом 1 – этот элемент 2, он не равен ключу и последний в списке, а значит поиск можно завершать. Таким образом вы не рассмотрели один из элементов и он так и остался в списке после выполнения процедуры удаления

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/task_6.1.c
> +                putToHashMap(starMap1, wrapString(system), wrapPointer(starDirection));
Вы ради этого городили костыли с поддержкой одинаковых ключей? Просто храните в мапе список.

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/task_6.1.c
> +            }
Чтение списка азимутов у вас повторяется минимум два раза – можно вынести в отдельную функцию и тем самым разгрузить немного main

2021-12-14 03:05 UTC, ArtyomLobanov commented on Homework6/task_6.1.c
> +            for (int i = getListSize(starMap1->hashTable[systemHash]->list) - 1; i >= 0; --i) {
Ой, лезть во внутренности структуры данных из не относящихся к её реализации файлов плохая идея. Код здесь ничего не знает о инвариантах работы структуры и может привести её в какое-то неконсистентное состояние. Да, и тот и другой код писали вы, но редактировать их в будущем вы можете независимо и это может привести к трудно отлавливаемым багам.

2021-12-23 20:18 UTC, ArtyomKopan commented on Homework6/hash_map.c
> +List* getHashMapElements(HashMap* map, Value key)
В новом коммите я исправил это, только поправил не функцию putToHashTable, а функцию addListElement

2021-12-24 11:52 UTC, ArtyomLobanov requested changes

2021-12-24 11:52 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +List* getHashMapElements(HashMap* map, Value key)
А зачем вы пытаетесь сохранить такой интерфейс? По сути вы теперь возвращаете список максимум из одного элемента.  Почему в таком случае не возвращать сам элемент?

2021-12-24 11:52 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +        map->hashTable[i] = makeNewHashMapElement();
Просто увеличить таблицу недостаточно. Вот у вас есть элемент. Его честный хеш – 13. У вас есть таблица размера 4. Вы считаете остаток от деления 13 на 4 и в итоге кладёте элемент в корзину с индексом 1. Затем вы решили удвоить количество корзин – теперь у вас их 8. В вашей реализации наш элемент всё ещё лежит в корзине с индексом 1. Но если кто-то попытается найти этот элемент, то он снова посчитает хеш (13), возьмёт остаток от деления на 8 (новый размер таблицы) и пойдёт безуспешно искать элемент в корзине с индексом 5.

2021-12-24 11:58 UTC, ArtyomKopan commented on Homework6/hash_map.c
> +        map->hashTable[i] = makeNewHashMapElement();
То есть после каждого увеличения размера нужно проходить по всей таблице и пересчитывать хэши?

2021-12-24 12:04 UTC, ArtyomLobanov commented on Homework6/hash_map.c
> +        map->hashTable[i] = makeNewHashMapElement();
И перекладывать элементы, да

2021-12-24 14:31 UTC, ArtyomKopan commented
Я добавил функцию, которая возвращает один элемент, но оставил и старую, которая возвращает список (без неё не работает поиск в хэш-таблице starMap1)

2021-12-24 15:57 UTC, ArtyomLobanov approved these changes
Ну, допустим

2022-04-02 18:32 UTC, merged