[SPBU-21.B10] Task 6.2 Копань Артём
ArtyomKopan/Programming_homeworks_1 pull request #20
Opened 2021-11-15 20:51 UTC by ArtyomKopan

2021-12-14 03:14 UTC, ArtyomLobanov requested changes
Там в задании ещё вопрос был:

> Кстати, а какую хеш-функцию вы бы использовали, если бы требовалось считать одинаковыми числа, отличающиеся меньше, чем на eps? Напишите свои мысли в комментарии к пул-реквесту.

2021-12-14 03:14 UTC, ArtyomLobanov commented on Homework6/task_6.2.c
> +                    s[i] = '.';
Ой, сорри. Это мой косяк. Чёртова локализация.

2021-12-14 03:14 UTC, ArtyomLobanov commented on Homework6/task_6.2.c
> +            fprintf(outputFile, "%i\n", index);
Стоит всё же проверять, что искомая точка нашлась и вы не пытаетесь обратиться по нулевому указателю.

2021-12-14 03:14 UTC, ArtyomLobanov commented on Homework6/task_6.2.c
> +            putToHashMap(map, wrapDouble(x / y), wrapInt(index));
Эм, а откуда у вас уверенность, что частное двух double-ов – уникальное значение? У вас даже не коллизия хешей, у вас корректное значение затрётся, если сначала добавить точку (2, 1), а затем (4, 2). У вас же даже структура готовая есть – Pair. Почему вы её не используете?

2021-12-23 21:13 UTC, ArtyomKopan commented
Если считать, что a == a+-eps, то можно находить хэш от a, перед этим округлив a до порядка eps (скажем, если eps = 10^-6, то округляем a до миллионных)

2021-12-24 12:03 UTC, ArtyomLobanov approved these changes
Что касается хеширования с погрешностью, то лучше хешировать не один значением, а двумя соседними референсными точками из сетки. Так мы можем гарантировать, что для пары близких точек хотя бы одно значение совпадёт.

2022-05-24 18:57 UTC, merged