C. Test #2. Task 2. Артём Копань
ArtyomKopan/Programming_homeworks_1 pull request #22
Opened 2021-11-16 09:18 UTC by ArtyomKopan

Если мы обозначим длину первого массива n, а длину второго m, то сложность алгоритма будет равна
O((n + m) * log(n + m)), т.к. здесь используется алгоритм сортировки слиянием

2021-11-16 11:15 UTC, ArtyomKopan commented
Почему-то функция merge из модуля mergeSort.c не сработала, поэтому мне пришлось по-быстрому написать её в main (не успел выделить в отдельную функцию).
Тогда программа из второго коммита будет работать за O(n + m)

2021-11-18 08:16 UTC, SpirinEgor requested changes
Кажется тут совсем всё не то.
1. Если смотреть по дедлайну, то там вообще была реализована сортировка. Тут она явно не нужна, и видать она ещё и не работает :(
2. Если смотреть на конечный результат, то там есть отголоски мерджа, но выглядит странно очень. Алгоритм как бы есть, но его использование вызывает недоумение.

Сложность хоть и правильно оценил, этого недостаточно :(

2021-11-18 08:16 UTC, SpirinEgor commented on Testwork2/test_task_2.2.c
> +        unitedArray[vasyaNotesCount + i] = petyaNotes[i];
Но это же не мердж :(

2021-11-18 08:16 UTC, SpirinEgor commented on Testwork2/test_task_2.2.c
> +        printf("%i ", unitedArray[k]);
Вообще странный порядок действий, положить в массив как есть, а потом выводить в нужном порядке.
Кажется первый шаг лишний, с таким же успехом можно было сразу принтить из исходных массивов

2021-11-18 08:16 UTC, closed without merging