[SPBU-21.B10] Task 8.2 Артём Копань
ArtyomKopan/Programming_homeworks_1 pull request #26
Opened 2021-11-28 22:57 UTC by ArtyomKopan

Решение полностью рабочее, но автомат в main инициализируется неэлегантно. Я хочу ещё допилить инициализацию автомата с помощью отдельного текстового файла

2021-11-29 08:55 UTC, ArtyomKopan commented
Добавил файловый ввод описания автомата (описание автомата для распознавания чисел находится в файле automaton_description.txt)

2021-12-11 13:28 UTC, SpirinEgor requested changes
Выглядит хорошо, в основном надо поправить логику обработки входа

2021-12-11 13:28 UTC, SpirinEgor commented on Homework8/automaton.c
> +bool isCorrect(Automaton* automaton, char* word, int startState)
В DFA стартовое состояние фиксировано и задано заранее, довольно странно его в функцию передавать. Скорее это ещё один параметр при создание.

2021-12-11 13:28 UTC, SpirinEgor commented on Homework8/automaton.c
> +                (transitionValue.type == CHAR_TYPE && *pointer == getChar(transitionValue)) || (transitionValue.type == STRING_TYPE && strcmp(getString(transitionValue), "digit") == 0 && isDigit(*poi
Весь этот if выглядит страшно, а вот эта строчка ещё хуже.
Общая рекомендация не вылазить за 120 символов, это оптимально для большинства современных мониторов.

2021-12-11 13:28 UTC, SpirinEgor commented on Homework8/automaton.c
> +        return false;
Страшная конструкция, запиши аккуратнее

2021-12-11 13:28 UTC, SpirinEgor commented on Homework8/automaton.h
> +} Automaton;
Ещё раз повторюсь, что писать структуры в хедере нарушает инкапсуляцию. Код, использующий автомат, будет знать об его особенностях, сможет напрямую работать с его полями.

2021-12-11 13:28 UTC, SpirinEgor commented on Homework8/list.c
> +List* makeNewList()
Мы же уже не один раз лист реализовывали, неужели нельзя использовать имеющиеся реализации?

2021-12-11 13:28 UTC, SpirinEgor commented on Homework8/values.h
> +#pragma pack(pop)
Выглядит интересно, но кажется перебор :)
В плане, излишние абстракции, которые не сильно оптимизируют код, но запутывают понимание.

2021-12-11 13:28 UTC, SpirinEgor commented on Homework8/values.h
> +#pragma pack(pop)
Кстати, pragma, насколько знаю, процессорные штуки, не факт что они будут работать, например, у меня.
Хотя вроде бы какие-то стандарты уже есть

2021-12-11 13:40 UTC, ArtyomKopan commented on Homework8/values.h
> +#pragma pack(pop)
А вот это не мой код, этот шаблон нам дал Артём Лобанов для домашки про АВЛ-деревья. Я только добавил поддержку char

2021-12-11 13:41 UTC, ArtyomKopan commented on Homework8/automaton.c
> +                (transitionValue.type == CHAR_TYPE && *pointer == getChar(transitionValue)) || (transitionValue.type == STRING_TYPE && strcmp(getString(transitionValue), "digit") == 0 && isDigit(*poi
Я хотел разбить этот if по нескольким строчкам, но линтер не даёт так сделать

2021-12-11 13:42 UTC, ArtyomKopan commented on Homework8/list.c
> +List* makeNewList()
Ну мы же реализовывали его не с универсальным типом данных. А это просто copypast уже имеющегося листа, просто теперь он универсальный

2021-12-11 13:48 UTC, SpirinEgor commented on Homework8/list.c
> +List* makeNewList()
А зачем ты делаешь копипасту, а не модифицируешь имеющуюся версию?

2021-12-11 13:48 UTC, SpirinEgor commented on Homework8/values.h
> +#pragma pack(pop)
А зачем ты делаешь копипасту, а не модифицируешь имеющуюся версию?

2021-12-11 13:49 UTC, ArtyomKopan commented on Homework8/list.c
> +List* makeNewList()
то есть файл list из library?

2021-12-11 13:57 UTC, SpirinEgor commented on Homework8/automaton.c
> +                (transitionValue.type == CHAR_TYPE && *pointer == getChar(transitionValue)) || (transitionValue.type == STRING_TYPE && strcmp(getString(transitionValue), "digit") == 0 && isDigit(*poi
Ну это не повод оставить как есть :)
Можно вынести в отдельную функцию, например

2021-12-11 13:57 UTC, SpirinEgor commented on Homework8/list.c
> +List* makeNewList()
Ага

2021-12-21 07:13 UTC, SpirinEgor requested changes
Надо бы удалить лишние файлы

2021-12-21 07:13 UTC, SpirinEgor commented on Homework8/automaton.c
> +    return (transitionValue.type == CHAR_TYPE && *pointer == getChar(transitionValue)) || (transitionValue.type == STRING_TYPE && strcmp(getString(transitionValue), "digit") == 0 && isDigit(*pointer)
Ну проблема длинных строчек не решилась. Но спасибо за отдельную функцию :)

2021-12-21 07:13 UTC, SpirinEgor commented on Homework8/values.c
> +#include "values.h"
Аналогичный файл есть и в library теперь, копипасту надо бы почистить

2021-12-21 07:13 UTC, SpirinEgor commented on Homework8/values.h
> +#ifndef SPBU_C_HOMEWORKS_VALUES_H
И это теперь можно удалить

2021-12-23 09:58 UTC, SpirinEgor approved these changes

2021-12-23 09:58 UTC, merged