[SPBU-21.B10] Task 1.2 Копань Артём
ArtyomKopan/Programming_homeworks_1 pull request #3
Opened 2021-09-18 13:39 UTC by ArtyomKopan

2021-09-19 15:45 UTC, SpirinEgor commented
В пр затесались файлы первой задачи. Видимо ты делал чекаут от ветки с первой домашкой. Так как ее влил, то необходимо обновить эту ветку:
```
git pull origin master
```

2021-09-19 15:59 UTC, ArtyomKopan commented
Сделал
--
Отправлено из Mail.ru для Android воскресенье, 19 сентября 2021г., 18:45 +03:00 от Egor Spirin  ***@***.*** :

>В пр затесались файлы первой задачи. Видимо ты делал чекаут от ветки с первой домашкой. Так как ее влил, то необходимо обновить эту ветку:
>git pull origin master
>
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .

2021-09-22 10:05 UTC, SpirinEgor requested changes

2021-09-22 10:05 UTC, SpirinEgor commented on Homework1/task_2.c
> +const int INF = (int)1e9;
В реальном мире порой сложно придумывать ограничения. Да и не нужны они порой. Эта задача спокойно решается без вот таких вот _олимпиадных_ констант

2021-09-22 10:05 UTC, SpirinEgor commented on Homework1/task_2.c
> +    int maximumMoreThanOnes = getMaximumMoreThanOnce(array, arraySize);
Совсем не обрабатывается случай, если такого элемента нет

2021-09-22 11:36 UTC, ArtyomKopan commented on Homework1/task_2.c
> +    int maximumMoreThanOnes = getMaximumMoreThanOnce(array, arraySize);
Исправил эти ошибки

2021-09-23 10:51 UTC, SpirinEgor requested changes

2021-09-23 10:51 UTC, SpirinEgor commented on Homework1/task_2.c
> +bool isMaximumExist = false;
Не, глобальные переменные еще хуже, чем просто какая-то константа. У тебя это значение любой подменить может. 

Чтобы избавиться от нее попробуй реализовать так: функция возвращает не элемент, а позицию элемента в массиве. Тогда если вернулось что-то не то, например, -1, то такого элемента не существует.

2021-09-23 10:51 UTC, SpirinEgor commented on Homework1/task_2.c
> +    int* array = (int*)calloc(arraySize, sizeof(int));
А освободить память в конце?

2021-09-24 10:32 UTC, SpirinEgor reviewed
1. Течет память (не освобождается массив, который на куче создал)
2. Что-то ты перестарался, у тебя почему-то task_1.c удаляется в этом пр.

2021-09-24 10:32 UTC, SpirinEgor commented on Homework1/task_2.c
> +    int* array = (int*)calloc(arraySize, sizeof(int));
А это поправить?

2021-09-24 11:29 UTC, SpirinEgor approved these changes

2021-09-24 11:29 UTC, merged