{SPBU-21.B10] Task 1.3 Копань Артём
ArtyomKopan/Programming_homeworks_1 pull request #6
Opened 2021-09-19 19:22 UTC by ArtyomKopan

2021-09-22 10:07 UTC, SpirinEgor requested changes

2021-09-22 10:07 UTC, SpirinEgor commented on Homework1/task_3.c
> +    }
Решение задачи можно и в отдельную функцию вынести, она хоть и маленькая, но представляет полноценный и независимый логический блок

2021-09-22 10:07 UTC, SpirinEgor commented on Homework1/task_3.c
> +    */
А зачем это тут?

2021-09-22 11:36 UTC, ArtyomKopan commented on Homework1/task_3.c
> +    */
Забыл удалить мёртвый код

2021-09-23 10:53 UTC, SpirinEgor approved these changes

2021-09-23 10:54 UTC, merged