[SPBU-21.B10] Task 2.1 Копань Артём
ArtyomKopan/Programming_homeworks_1 pull request #7
Opened 2021-10-03 15:38 UTC by ArtyomKopan

2021-10-07 15:42 UTC, ArtyomLobanov requested changes
Время на исправление – неделя

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +DictElement* makeNewDictElement(const char* key, int value)
Стайлгайд запрещает сокращать слова, за исключением популярных аббревиатур.

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +    if (dict->head == NULL) {
По [стайлгайду](https://webkit.org/code-style-guidelines/#braces) проверки на NULL должны быть неявными.

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +        penultimateElement->nextElement = dict->tail;
```cpp
dict->tail->nextElement = newElement;
dict->tail = newElement;
```

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +        if (strcmp(currentElement->key, key) == 0)
for-ом такая логика в одну строку пишется
```cpp
for (DictElement* current = dict->head; current ; current = current->nextElement) {
    ...
}
```

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +            return true;
Не правда ли этот код дублируется в функции get? Давайте вынесем эту логику в отдельную функцию.

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +        free(currentElement);
А память, выделенную под хранение локальной копии ключей, кто освободит?

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/task_2.1.c
> +        printf("File open error!");
Если не получилось открыть только один из двух файлов, то второй перед завершением работы нужно закрыть

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/task_2.1.c
> +    while (currentElement != NULL) {
Опять же сравнение с NULL должны быть неявными

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/task_2.1.c
> +    while (currentElement != NULL) {
И опять же цикл for здесь лучше подходит

2021-10-07 15:42 UTC, ArtyomLobanov commented on Homework2/task_2.1.c
> +                    currentElement->value++;
Метод put обладает семантикой присвоения. Если элемент уже присутствует в структуре данных, то старое значение value перезаписывается. Иными словами, ваша работа со структурой должны здесь выглядеть так:
```cpp
put(map, hasKey(map, word) ? get(map, word) + 1 : 1);
```

2021-10-09 10:52 UTC, ArtyomKopan commented on Homework2/dictionary.c
> +            return true;
Но ведь в get этот код должен возвращать значение элемента, а в hasKey - просто true, если такой ключ существует

2021-10-09 16:47 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +            return true;
Пусть find возвращает указатель на искомый элемент, либо NULL, если такого нет. В hasKey будем сравнивать указатель с NULL, а в get обращаться к полю найденного элемента

2021-10-09 16:47 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +            return true;
Пусть find возвращает указатель на искомый элемент, либо NULL, если такого нет. В hasKey будем сравнивать указатель с NULL, а в get обращаться к полю найденного элемента

2021-10-09 16:52 UTC, ArtyomLobanov requested changes

2021-10-09 16:52 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +    if (!hasKey(dict, key)) {
И put через find тоже легче пишется.
```cpp
void put(...) 
{
    Element* element = find(map, key);
    if (element)
          element->value = value;
    else {
         element = makeNewDictionaryElement(key, value);
         ...
    }   
}

2021-10-09 16:58 UTC, ArtyomKopan commented on Homework2/dictionary.c
> +            return true;
исправил

2021-10-14 11:30 UTC, ArtyomLobanov requested changes
Да исправьте вы функцию освобождения памяти из-под Dictionary и закроем эту домашку. Там нужно буквально одну строку добавить. Смотрите, где-то в памяти лежит DictionaryElement. Пусть он занимает адреса с 239 по 250. Где-то в нём лежит указатель (по сути своей просто число – адрес куска памяти, где лежит сохранённый ключ). Скажем, пусть element->key численно равен 566 и, соответственно, в в памяти адреса с 566 до 600 занимает какая-то строка. Вызывая free(currentElement) вы освобождаете первый кусок памяти и безвозвратно теряете указатель на второй.

2021-10-14 11:30 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +        return 0; // элемент не найден
А зачем отдельно обрабатывать этот случай? find же вполне умеет работать с пустой структурой

2021-10-14 11:30 UTC, ArtyomLobanov commented on Homework2/dictionary.c
> +        return 0; // элемент не найден
Можно в одну строку
```cpp
return foundElement ? foundElement->value : defaultValue;
```

2021-10-14 19:52 UTC, ArtyomLobanov approved these changes

2021-10-14 19:52 UTC, ArtyomLobanov commented
Ок, зачтено

2021-10-14 19:52 UTC, merged