[SPBU-21.B10] Task 2.2 Копань Артём
ArtyomKopan/Programming_homeworks_1 pull request #8
Opened 2021-10-04 19:35 UTC by ArtyomKopan

2021-10-14 13:25 UTC, ArtyomLobanov requested changes
Исправите за неделю – поставлю полный балл.

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/list.c
> +    List* lst = malloc(sizeof(List));
Стайлгайд запрещает использовать сокращения, кроме общеупотребляемых аббревиатур.

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/list.c
> +    } else if (lst->listSize >= position) {
Тут знак сравнения не верный, кажется. Если `lst->listSize >= position` (позиция не превосходит размер списка), значит мы вставляем элемент в центр списка, а не в конец.

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/list.c
> +            prevElement = prevElement->next;
Вот предположим для удоства, что этот for мы вынесли в отдельную функцию get(List* list, int position). Тогда весь этот метод можно переписать так:
```cpp
bool addElement(List* list, char data, int position)
{
    if (position < 0 || position > list->size) 
        return false; 
    ListElement* element = makeNewListElement(data);
    element->previous = position > 0 ? get(list, position - 1) : NULL;
    element->next = previous ? previous->next : NULL;
    if (element->next)
        element->next->previous = element;
    else
        list->tail = element;
    if (element->previous)
        element->preious->next = element;
    else
        list->head = element;
    list->size++;
    return true;
}
```
А если использовать силу указателей на полную, то даже так
```cpp
bool addElement(List* list, char data, int position)
{
    if (position < 0 || position > list->size) 
        return false; 
    ListElement* element = makeNewListElement(data);
    ListElement** nextLink = position > 0 ? &get(list, position - 1)->next : &list->head;
    ListElement** previousLink = *nextLink ? &(*nextLink)->previous : &list->tail;
    element->previous = *previousLink;
    *previousLink = element;
    element->next = *nextLink;
    *nextLink = element;
    list->size++;
    return true;
}
```

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/list.c
> +                (currentElement->next)->prev = currentElement->prev;
А теперь давайте это перепишем, используя гиптотетическую функцию get:
```cpp
bool deleteElementAt(List* lst, int position)
{
    if (position < 0 || position >= list->size)
        return false;
    ListElement* element = get(list, position);
    ... // обновили ссылки у предыдущего/следующего элемента
    ... // обновили ссылки на голову/хвост списка
    free(element);
    list->size--;
    return true;
}
```
Линейный код всегда проще читать

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/list.c
> +            free(currentElement);
А если это был первый/последний элемент? Кто обновит указатели на голову/хвост списка?

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/list.c
> +        currentElement = nextElement;
Через for чуть компактнее
```cpp
ListElement* next = NULL:
for (ListElement* current = list->head; current; current = next) {
    next = current->next;
    free(current);
}

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/list.c
> +    char str[2048];
Если вы используете буффер для увеличения скорости записи, то не стоит беспокоиться – стандартные сишные функции и так используют буфферезированный ввод/вывод. Так что в целом можно спокойно использовать `fprintf("%c", current->data);`. 
Если вы всё же хотите выводить данные через промежуточный буффер, то
1. Пишите это так, чтобы это работало с произвольными по длине списками
2. Не забывайте про нулевой символ
```cpp
char buffer[BUFFER_SIZE];
int position = 0;
for (ListElement* current = list->head; current; current = current->next) {
    buffer[position++] = current->data;
    if (position == BUFFER_SIZE - 1) {
        buffer[position++] = '\0';
        fprintf(file, "%s", buffer);
        position = 0;
    }
}
buffer[position++] = '\0';
fprintf(file, "%s/n", buffer);
```

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/list.h
> +typedef struct ListElement ListElement;
Зачем у вас typedef два раза повторён? И почем тогда не написать так:
```cpp
typedef struct List {
    ListElement* head;
    ListElement* tail;
    int listSize;
} List;
```

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +    while (currentElement) {
Откуда у вас всех такая нелюбовь к for-ам
```cpp
for (ListElement* start = lst->head; start; start = start->next) {
   ...
}
```

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +        if (currentElement->data == pattern[0]) {
А зачем это отдельно проверять? Какая разница – здесь или внутри вложенного for-а?

"_Преждевременная оптимизация – корень всех зол_" (с) кто-то умный

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +            for (int j = 1; j < strlen(pattern); ++j) {
strlen – крайне дорогая операция. Она каждый раз бежит по всей строке, пока не найдёт нулевой символ. Не нужно использовать её в условии цикла.

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +            for (int j = 1; j < strlen(pattern); ++j) {
Вместо явного использования длины, останавливайте поиск, когда стретите нулевой символ
```cpp
ListElement* element = currentElement;
for (char* pointer = pattern; ; pointer++) {
    if (!*pointer) // дошли до нулевого символа
        return index;
    if (!element || element->data != *pointer)
        break;
    element = element->next;
}
```

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +                if (now == NULL || now->data != pattern[j]) {
По [стайлгайду](https://webkit.org/code-style-guidelines/#null-false-and-zero) проверки на NULL должны быть неявными

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +void delete (List* lst, char start[], char end[])
Разницы между `foo(char data[])` и `foo(char* data)` нет абсолютно никакой. Но второй вариант является общепринятым, поэтому лучше везде используйте его.

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +    int endIndex = search(lst, end) + strlen(end);
Бага. Для строки "ABACABA" и запроса "DELETE CA AB" вы должны найти вот эти фрагменты "ABA[CA][BA]", а не вот эти "[AB]A[CA]BA". Иными словами, начало фрагмента end нужно искать строго позже конца найденного фрагмента start. И убеждайтесь, что фрагменты удалось найти. Если я не налажал, то в тестовом задании такой ситуации возникнуть не должно, но это поможет вам легче обнаружить баги в вашей реализации.

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +        deleteElementByIndex(lst, startIndex);
Удалить несколько подрядидущих элементов из связного списка можно за линейное время. А у вас это будет работать за квадрат (каждая операция deleteElementByIndex выполняется за время, пропорциональное длине списка). Давайте реализуем функцию `deleteRange(List* list, int start, int end)` в list.h, которая будет эффективно удалять фрагменты списка.

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +    delete (lst, template, template);
Лишний пробел

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +    for (int i = 0; i < strlen(fragment); ++i)
Опять же, не используйте strlen в условии цикла

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +        addElement(lst, fragment[i], startIndex + i);
И вставить последовательность элементов можно тоже за линию, а не за квадрат. Реализуйте функцию `addElements(List* list, int position, char* data, int size)`, которая будет эффективно вставлять элементы в связный список

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +        printf("File open error!");
Не забывайте закрывать успешно открытые файлы

2021-10-14 13:25 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +    int lengthDNA = 0, operationsCount = 0;
Объявлять несколько переменных на одной строке – дурной тон. Мешает понимать где какая переменная была объявлена и может ввести в заблуждение в случае ссылочных типов: в конструкции `int* a, b;` переменная `a` имеет тип `int*`, а переменная `b` – `int`.

2021-10-14 13:26 UTC, ArtyomLobanov commented
И исправьте конфликты с мастером, пожалуйста

2021-10-14 19:27 UTC, ArtyomKopan commented on Homework2/task_2.2.c
> +    delete (lst, template, template);
Почему-то Clang так форматирует функцию delete

2021-10-15 12:41 UTC, ArtyomLobanov commented
И решите конфликты с мастером, пожалуйста

2021-11-04 14:54 UTC, ArtyomLobanov approved these changes
Close enought. Исправите Undefined Behaviour – поставлю полный балл. Остальное в целом исправлять не обязательно, но поймите, почему 10 if-ов в каждой операции над двусвязным списоком излишни. Пока ставлю 2.5

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/list.c
> +        return list->head;
Этот if лишний, кстати. Если position == 0, то for выполнится 0 раз и мы так же вернём list->head

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/list.c
> +        element->next = element->previous ? element->previous->next : NULL;
И вот этот if можно было в одну строку записать. Если previous получился NULL, то либо мы добавляем элемент в начало списка, либо список пуст (т.е. можно считать, что опять в начало добавляем, но в этом случае list->head == NULL). 
```cpp
element->next = element->previous ? element->previous->next : list->head;
```

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/list.c
> +            temp[i]->next = temp[i + 1];
Можно без вложенных if-ов
```cpp
for (int i = 0; i< dataSize - 1; i++) {
    tmp[i]->next = tmp[i + 1];
    tmp[i + 1]->previous = tmp[I];
}
```

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/list.c
> +    ListElement** temp = malloc(sizeof(ListElement) * dataSize);
sizeof(ListElement) – это память, которая необходима для хранения структуры ListElement. Грубо говоря, 1 байт под char и по 8 байтов под два указателя. А в массиве вы на самом деле храните не сами элементы, а лишь указатели на них. Все указатели имеют один размер (правда, различный в зависимости от платформы). Вы выделяете слишком много памяти. Достаточно будет `malloc(sizeof(ListElement*) * dataSize)`

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/list.c
> +        list->tail = temp[dataSize - 1];
А мы верим, что dataSize > 0? По-хорошему, раз уж вы обращаетесь к элементам массива указателей, нужно было сделать отсечение в начале тела метода, что в случае пустой последовательности ничего в списке не меняем и завершаем работу.

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/list.c
> +    }
Какая-то кошмарно сложная логика получается. Давайте попробуем сократить:
```cpp
if (!previous)  // Добавляем в начало списка (ну либо список пуст, тогда любое добавление - добавление в начало)
    list->head = temp[0];
else { // Есть предыдущий элемент
    temp[0]->previous = previous;
    previous->next = temp[0];
}
if (!next) // Добавляем в конец (либо список пуст и всё равно можно считать, что добавляем в конец)
    list->tail = temp[dataSize - 1];
else { // Следующий элемент существует
    temp[dataSize -1]->next = next;
    next->previous = temp[dataSize - 1];
}
```
12 строк вместо 27

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/list.c
> +    element->next->previous = element->previous;
element->next может быть NULL – тогда вы получите здесь Undefined Behaviour.
На самом деле эти строки можно объединить с if-ами ниже и получить:
```cpp
if (element->next) // следующий элемент существует
    element->next->previous = element->previous;
else // удаляем последний элемент списка
    list->tail = element->previous;
if (element->previous) // предыдущий элемент существует
    element->previous->next = element->next;
else // удаляем первый элемент списка
    list->head = element->next;
```

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/list.c
> +    }
Опять же нет смысла разбирать эти ситуации по отдельности:
```cpp
void deleteRange(List* list, int start, int end)
{
    if (/*некорректные входные данные*/)
        return;
    ListElement* before = get(list, start - 1);
    ListElement* after = get(list, end + 1);
    ListElement* next = NULL;
    for (ListElement* element = get(list, start); element != after; element = next) {
        next = element->next;
        free(element);
    }
    if (before)
        before->next = after;
    else 
        list->head = after;
    if (after)
        after->previous = before;
    else
        list->tail = before;
    list->listSize -= (end - start + 1);
}
```

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +    int startIndex = search(list, start, -1) + strlen(start);
Неплохо было бы добавить проверку, что последовательность нашлась

2021-11-04 14:54 UTC, ArtyomLobanov commented on Homework2/task_2.2.c
> +    delete (list, template, template);
Видимо линтер путает функцию delete с ключевым словом из C++ и поэтому настаивает именно на такой расстановке пробелов. Можно переименовать в remove или deleteFragment.

2021-12-16 10:41 UTC, ArtyomLobanov commented
Ок, решите конфликт и можно сливать с мастером

2021-12-23 11:34 UTC, merged